#
# GNUmakefile for CommonCrypto. Derived by Niels Grewe from a rotting torso 
# generated by a segfaulting pbxbuild.
#

shared=yes

include $(GNUSTEP_MAKEFILES)/common.make

LIBRARY_NAME=CommonCrypto

VERSION=0

CC=clang

CommonCrypto_C_FILES=\
	Source/AESedp/AES.c\
	Source/BlockCipher.c\
	Source/CAST/c_ecb.c\
	Source/CAST/c_enc.c\
	Source/CAST/c_skey.c\
	Source/CAST/ccCast.c\
	Source/CommonCrypto.c\
	Source/CommonHMAC.c\
	Source/Digest/md2_dgst.c\
	Source/Digest/md4_dgst.c\
	Source/Digest/md5_dgst.c\
	Source/Digest/sha1.c\
	Source/Digest/sha2.c\
	Source/RC2/ccRC2.c\
	Source/RC2/rc2.c\
	Source/RC4/rc4_enc.c\
	Source/RC4/rc4_skey.c\
	Source/StreamCipher.c\
	Source/ccOpenssl/des_enc.c\
	Source/ccOpenssl/opensslDES.c\
	Source/ccOpenssl/set_key.c

CommonCrypto_HEADER_FILES=\
	CommonCrypto.h\
	CommonDigest.h\
	CommonHMAC.h

CommonCrypto_HEADER_FILES_DIR=\
	CommonCrypto

CommonCrypto_HEADER_FILES_INSTALL_DIR=\
	CommonCrypto

CommonCrypto_INCLUDE_DIRS=\
	-I./CommonCrypto\
	-I./Source/CAST\
	-I./$(SRCROOT)\
	-I./Source/RC2\
	-I./Source/RC4\
	-I./Source/AESedp\
	-I./$(SRCROOT)/Source\
	-I./Source/GladmanAES\
	-I./Source/ccOpenssl\
	-I./Source/CommonCrypto\
	-I./Source\
	-I./Source/Digest

# Rules imported from libobjc2 to build assembly targets. Strangely enough, the
# GNU binutils assembler barfs on some of these files, and the llvm MC assembler
# in clang on others. So we need to choose the assembler accordingly:

CommonCrypto_OBJ_FILES = \
$(GNUSTEP_OBJ_INSTANCE_DIR)/Source/Digest/sha1edpLittleEndian.s.clang-as$(OEXT) \
$(GNUSTEP_OBJ_INSTANCE_DIR)/Source/Digest/sha1edpBigEndian.s.clang-as$(OEXT) \
$(GNUSTEP_OBJ_INSTANCE_DIR)/Source/AESedp/Intel/AES.s.extern-as$(OEXT) \
$(GNUSTEP_OBJ_INSTANCE_DIR)/Source/AESedp/Intel/EncryptCBC.s.extern-as$(OEXT) \
$(GNUSTEP_OBJ_INSTANCE_DIR)/Source/AESedp/Intel/DecryptCBC.s.extern-as$(OEXT) 

# Add rule for producing object files from assembler
$(GNUSTEP_OBJ_INSTANCE_DIR)/%.s.clang-as$(OEXT) : %.s
	$(ECHO_COMPILING)$(CC) -integrated-as -x assembler-with-cpp $< -c \
              $(filter-out $($<_FILE_FILTER_OUT_FLAGS),$(ALL_CPPFLAGS)\
                                                        $(ALL_CFLAGS)) \
              $($<_FILE_FLAGS) -o $@$(END_ECHO)

$(GNUSTEP_OBJ_INSTANCE_DIR)/%.s.extern-as$(OEXT) : %.s
	$(ECHO_COMPILING)$(CC) -no-integrated-as -x assembler-with-cpp $< -c \
              $(filter-out $($<_FILE_FILTER_OUT_FLAGS),$(ALL_CPPFLAGS)\
                                                        $(ALL_CFLAGS)) \
              $($<_FILE_FLAGS) -o $@$(END_ECHO)

CommonCrypto_LIB_DIRS=

ADDITIONAL_CPPFLAGS+= -DGNUSTEP -DNDEBUG -DTARGET_CPU_X86_64=1 -DTARGET_OS_UNIX=1 -DAES_ASM
include $(GNUSTEP_MAKEFILES)/library.make
-include GNUmakefile.postamble
